kind: pipeline
type: docker
name: default

steps:
- name: greeting
  image: alpine
  commands:
  - echo hello
  - echo world


- name: second_step
  image: alpine
  commands:
  - echo hello2
  - echo world2
  depends_on:
  - greeting
  - second_step
